#!/usr/bin/env bash

while read oldrev newrev ref
do
    BRANCH=$(git rev-parse --symbolic --abbrev-ref $ref)
    if [[ $BRANCH == "master" ]]; then
        echo "Push received! deploying branch: ${BRANCH}..."
    else
        echo "Not master branch. Skipping."
    fi
done
