#!/usr/bin/env bash

set -xeo pipefail

whoami
pwd
env

while read oldrev newrev ref
do
    branch=$(git rev-parse --symbolic --abbrev-ref $ref)
    if [[ $branch == "master" ]]; then
        make sync
    fi
done