apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: k8s.azof.fr/azoff/registry:1.3.0
        ports:
        - containerPort: 5000
        env:
        - name: REGISTRY_HTTP_RELATIVEURLS
          value: 'true'
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: /run/secrets/nuc/registry.htpasswd
        - name: REGISTRY_HTTP_SECRET
          valueFrom:
            secretKeyRef:
              name: nuc
              key: registry.secret
        volumeMounts:
        - name: lib
          mountPath: /var/lib/registry
        - name: registry-htpasswd
          mountPath: /run/secrets/nuc/registry.htpasswd
          subPath: registry.htpasswd
          readOnly: true
      imagePullSecrets:
      - name: dockerconfigjson
      volumes:
      - name: lib
        persistentVolumeClaim:
          claimName: registry
      - name: registry-htpasswd
        secret:
          secretName: nuc
          items:
          - key: registry.htpasswd
            path: registry.htpasswd
