apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: k8s.azof.fr/azoff/registry:1.0.1
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: lib
          mountPath: /var/lib/registry
      imagePullSecrets:
      - name: dockerconfigjson
      volumes:
      - name: lib
        persistentVolumeClaim:
          claimName: registry
