---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: k8s.azof.fr/azoff/registry:1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        volumeMounts:
            - name: lib
              mountPath: /var/lib/registry
      volumes:
        - name: lib
          persistentVolumeClaim:
            claimName: registry
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  selector:
    app: registry
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000