version: "3.8"

services:

  nginx:
    init: true
    image: azoff/nginx
    build: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/static:/var/www/static

    networks:
      private:

networks:
  private:
