version: "3.8"

services:

  pdfgpt-server:
    build:
      context: pdf-gpt 
      target: langchain-serve-img
    network_mode: host
    env_file: .env
    working_dir: /app
    volumes:
      - ./pdf-gpt:/app

  pdfgpt-client:
    build:
      context: pdf-gpt
      target: pdf-gpt-img
    network_mode: host
    env_file: .env
    volumes:
      - ./pdf-gpt:/app

  nginx:
    init: true
    image: azoff/nginx
    build: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/vhosts:/var/www/vhosts
      - https-portal-data:/var/lib/https-portal
    network_mode: host
    env_file: .env
    environment:
      - STAGE=${CERT_STAGE:-local}
      - DOMAINS=
          static.azof.fr, 
          plex.azof.fr -> http://localhost:32400, 
          ${CCTV_LOGIN:-}cctv.azof.fr -> http://${CCTV_IP:-tinypilot.local}, 
          tx.azof.fr   -> http://localhost:9091,
          ${PDFGPT_LOGIN:-}pdf.azof.fr  -> http://localhost:7860,
          ${PDFGPT_LOGIN:-}api.pdf.azof.fr  -> http://localhost:8080

  plex:
    image: azoff/plex
    build: plex
    restart: unless-stopped
    volumes:
      - ${SHARED_MOUNT_PATH:-/tmp}/plex/data:/data:ro
      - ${SHARED_MOUNT_PATH:-/tmp}/plex/config:/config
      - ${PLEX_TRANSCODE_PATH:-/tmp/plex/transcode}:/transcode
    env_file: .env
    devices:
      - /dev/dri:/dev/dri
    network_mode: host
  
  transmission:
    image: azoff/transmission
    build: transmission
    restart: unless-stopped
    volumes:
      - ${SHARED_MOUNT_PATH:-/tmp}/plex/data:/downloads
      - ${SHARED_MOUNT_PATH:-/tmp}/transmission/config:/config
      - ${SHARED_MOUNT_PATH:-/tmp}/transmission/watch:/watch
    env_file: .env
    environment:
      - USER=${TRANSMISSION_USER:-transmission}
      - PASS=${TRANSMISSION_PASSWORD:-transmission}
    network_mode: service:vpn
    depends_on:
      - vpn
  
  vpn:
    image: azoff/vpn
    build: vpn
    environment:
      - ACTIVATION_CODE=${EXPRESSVPN_ACTIVATION_CODE}
    cap_add:
      - NET_ADMIN
    devices: 
      - /dev/net/tun
    stdin_open: true
    tty: true
    command: /bin/bash
    privileged: true
    restart: unless-stopped
    ports:
      # transmission / bittrorrent
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    
volumes:
  https-portal-data:
