version: "3.8"

services:

  nginx:
    init: true
    image: azoff/nginx
    build: nginx
    restart: unless-stopped
    ports:
      - '443:443'
    volumes:
      - ./nginx/vhosts:/var/www/vhosts
      - https-portal-data:/var/lib/https-portal
    networks:
      - private
    env_file: .env

  plex:
    image: azoff/plex
    build: plex
    restart: unless-stopped
    volumes:
      - ${SHARED_MOUNT_PATH}/plex/data:/data:ro
      - ${SHARED_MOUNT_PATH}/plex/config:/config
      - ${PLEX_TRANSCODE_PATH:-/tmp/plex/transcode}:/transcode
      - ./certbot/certs:/etc/nginx/certs:ro
      - ./certbot/letsencrypt:/etc/letsencrypt:ro
    env_file: .env
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    networks:
      - private

networks:
  private:

volumes:
  https-portal-data:
