version: "3.8"

services:

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - /tmp/redis:/data
    networks:
      - internal

  pdf:
    image: azoff/flask-pdf-tokenizer:1.11.2
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - REDIS_HOST=redis
    networks:
      - internal
      - default

  meater:
    image: azoff/meater:1.2.0
    ports:
      - 3000:${MEATER_BUN_PORT}
    environment:
      - BUN_HOST=${MEATER_BUN_HOST}
      - BUN_PORT=${MEATER_BUN_PORT}
      - GOOGLE_SHEET_ID=${MEATER_GOOGLE_SHEET_ID}
      - GOOGLE_MAP_ID=${MEATER_GOOGLE_MAP_ID}
      - GOOGLE_SERVICE_ACCOUNT_EMAIL=${MEATER_GOOGLE_SERVICE_ACCOUNT_EMAIL}
      - GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY=${MEATER_GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY}
    networks:
      - default

  nginx:
    init: true
    image: azoff/nginx
    build: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/vhosts:/var/www/vhosts
      - https-portal-data:/var/lib/https-portal
    network_mode: host
    env_file: .env
    environment:
      - STAGE=${CERT_STAGE:-local}
      - DOMAINS=
          cmt.azof.fr => https://carolyn.thayer.azof.fr,
          carolyn.thayer.azof.fr,
          static.azof.fr, 
          plex.azof.fr -> http://localhost:32400,
          meater.azof.fr -> http://localhost:3000,
          ${CCTV_LOGIN:-}@cctv.azof.fr -> http://${CCTV_IP:-tinypilot.local}, 
          tx.azof.fr   -> http://localhost:9091,
          ${PDF_LOGIN:-}@pdf.azof.fr  -> http://localhost:8000,

  plex:
    image: azoff/plex
    build: plex
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 10G
    volumes:
      - ${SHARED_MOUNT_PATH:-/tmp}/plex/data:/data:ro
      - ${SHARED_MOUNT_PATH:-/tmp}/plex/config:/config
      - ${PLEX_TRANSCODE_PATH:-/tmp/plex/transcode}:/transcode
    env_file: .env
    devices:
      - /dev/dri:/dev/dri
    network_mode: host
  
  transmission:
    image: azoff/transmission
    build: transmission
    restart: unless-stopped
    volumes:
      - ${SHARED_MOUNT_PATH:-/tmp}/plex/data:/downloads
      - ${SHARED_MOUNT_PATH:-/tmp}/transmission/config:/config
      - ${SHARED_MOUNT_PATH:-/tmp}/transmission/watch:/watch
    env_file: .env
    environment:
      - USER=${TRANSMISSION_USER:-transmission}
      - PASS=${TRANSMISSION_PASSWORD:-transmission}
    network_mode: service:vpn
    depends_on:
      - vpn
  
  vpn:
    image: azoff/vpn
    build: vpn
    environment:
      - ACTIVATION_CODE=${EXPRESSVPN_ACTIVATION_CODE}
    cap_add:
      - NET_ADMIN
    devices: 
      - /dev/net/tun
    stdin_open: true
    tty: true
    command: /bin/bash
    privileged: true
    restart: unless-stopped
    ports:
      # transmission / bittrorrent
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    
volumes:
  https-portal-data:

networks:
  internal:
  default: