services:

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - /tmp/redis:/data
    networks:
      - internal

  pdf:
    image: azoff/flask-pdf-tokenizer:1.15.2
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - REDIS_HOST=redis
    networks:
      - internal
      - default

  sftp:
    image: azoff/sftp
    build: sftp
    restart: unless-stopped
    ports:
      - 2222:22
    volumes:
      - ${SHARED_MOUNT_PATH:-/tmp}/sftp/home:/home
      - ${SHARED_MOUNT_PATH:-/tmp}/sftp/etc:/etc/sftp:ro
      - ${SHARED_MOUNT_PATH:-/tmp}/sftp/ssh:/etc/ssh
      - ./sftp/sshd_config:/etc/ssh/sshd_config:ro
      - ./sftp/set-permissions.sh:/etc/sftp.d/set-permissions.sh:ro
    command: 'jon::${UID:-1000}'
    networks:
      - default

  nginx:
    init: true
    image: azoff/nginx
    build: nginx
    restart: unless-stopped
    volumes:
      - ${SHARED_MOUNT_PATH:-/tmp}/sftp/home/carolyn/share/carolyn.thayer.azof.fr:/var/www/vhosts/carolyn.thayer.azof.fr:ro
      - https-portal-data:/var/lib/https-portal
    network_mode: host
    env_file: .env
    environment:
      - STAGE=${CERT_STAGE:-local}
      - DOMAINS=
          cmt.azof.fr => https://carolyn.thayer.azof.fr,
          carolyn.thayer.azof.fr,
          plex.azof.fr -> http://localhost:32400,
          ${CCTV_LOGIN:-}@cctv.azof.fr -> http://${CCTV_IP:-tinypilot.local}, 
          tx.azof.fr -> http://localhost:9091,
          ${PDF_LOGIN:-}@pdf.azof.fr  -> http://localhost:8000,
          ${CHANGEDETECTION_LOGIN:-}@changedetection.azof.fr  -> http://localhost:5000,

  changedetection:
    image: dgtlmoon/changedetection.io:latest
    volumes:
      - ${SHARED_MOUNT_PATH:-/tmp}/changedetection/datastore:/datastore
      # Configurable proxy list support, 
      # see https://github.com/dgtlmoon/changedetection.io/wiki/Proxy-configuration#proxy-list-support
      # - ./proxies.json:/datastore/proxies.json
    networks:
      - default
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - BASE_URL=${CHANGEDETECTION_BASE_URL:-https://changedetection.azof.fr}
      - HIDE_REFERER=true
      - FETCH_WORKERS=2
      - MINIMUM_SECONDS_RECHECK_TIME=1
      - DISABLE_VERSION_CHECK=true
      - TZ=America/Los_Angeles
    restart: unless-stopped

  plex:
    image: azoff/plex
    build: plex
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 10G
    volumes:
      - ${SHARED_MOUNT_PATH:-/tmp}/plex/data:/data:ro
      - ${SHARED_MOUNT_PATH:-/tmp}/plex/config:/config
      - ${PLEX_TRANSCODE_PATH:-/tmp/plex/transcode}:/transcode
    env_file: .env
    devices:
      - /dev/dri:/dev/dri
    network_mode: host
  
  transmission:
    image: azoff/transmission
    build: transmission
    restart: unless-stopped
    volumes:
      - ${SHARED_MOUNT_PATH:-/tmp}/plex/data:/downloads
      - ${SHARED_MOUNT_PATH:-/tmp}/transmission/config:/config
      - ${SHARED_MOUNT_PATH:-/tmp}/transmission/watch:/watch
    env_file: .env
    environment:
      - USER=${TRANSMISSION_USER:-transmission}
      - PASS=${TRANSMISSION_PASSWORD:-transmission}
    network_mode: service:vpn
    depends_on:
      - vpn
  
  vpn:
    image: azoff/vpn
    build: vpn
    environment:
      - ACTIVATION_CODE=${EXPRESSVPN_ACTIVATION_CODE}
    cap_add:
      - NET_ADMIN
    devices: 
      - /dev/net/tun
    stdin_open: true
    tty: true
    command: /bin/bash
    privileged: true
    restart: unless-stopped
    ports:
      # transmission / bittrorrent
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    
volumes:
  https-portal-data:

networks:
  internal:
  default: