version: "3.8"

services:

  nginx:
    init: true
    image: azoff/nginx
    build: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/static:/var/www/static
    networks:
      - private

  plex:
    image: azoff/plex
    build: plex
    restart: unless-stopped
    volumes:
      - ./plex/config:/config
      - /tmp/plex/transcode:/transcode
      - /media/plex:/data:ro
    env_file: .env
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    networks:
      - private

networks:
  private:
