version: "3.8"

services:

  nginx:
    init: true
    image: azoff/nginx
    build: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/vhosts:/var/www/vhosts
      - https-portal-data:/var/lib/https-portal
    network_mode: host
    env_file: .env

  plex:
    image: azoff/plex
    build: plex
    restart: unless-stopped
    volumes:
      - ${SHARED_MOUNT_PATH}/plex/data:/data:ro
      - ${SHARED_MOUNT_PATH}/plex/config:/config
      - ${PLEX_TRANSCODE_PATH:-/tmp/plex/transcode}:/transcode
    env_file: .env
    devices:
      - /dev/dri:/dev/dri
    network_mode: host
  
  transmission:
    image: azoff/transmission
    build: tranmission
    restart: unless-stopped
    volumes:
      - ${SHARED_MOUNT_PATH}/plex/data:/downloads
      - ${SHARED_MOUNT_PATH}/transmission/config:/config
      - ${SHARED_MOUNT_PATH}/transmission/watch:/watch
    env_file: .env
    environment:
      - USER=${TRANSMISSION_USER:-transmission}
      - PASS=${TRANSMISSION_PASS:-transmission}
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp

volumes:
  https-portal-data:
