apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: certrenew
spec:
  schedule: "@monthly"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: certrenew
            image: k8s.azof.fr/azoff/certbot:0.7.0
            command: ["certbot", "renew"]
            volumeMounts:
            - name: conf
              mountPath: /etc/letsencrypt
            - name: cloudflare-ini
              mountPath: /run/secrets/nuc/cloudflare.ini
              subPath: cloudflare.ini
              readOnly: true
          imagePullSecrets:
          - name: dockerconfigjson
          volumes:
          - name: conf
            persistentVolumeClaim:
              claimName: certbot
          - name: cloudflare-ini
            secret:
              secretName: nuc
              items:
              - key: cloudflare.ini
                path: cloudflare.ini
          restartPolicy: OnFailure