apiVersion: batch/v1
kind: Job
metadata:
  name: certonly
spec:
  template:
    spec:
      containers:
      - name: certonly
        image: k8s.azof.fr/azoff/certbot:0.6.2
        command: ["certbot", "certonly",
          # "--staging",
          "--force-renewal",
          "--agree-tos",
          "--non-interactive",
          "--email", "jon@azof.fr",
          "--dns-cloudflare",
          "--dns-cloudflare-credentials", "$CLOUDFLARE_INI_PATH",
          "--rsa-key-size", "4096",
          "-d", "*.azof.fr"
        ]
        volumeMounts:
        - name: conf
          mountPath: /etc/letsencrypt
        - name: cloudflare
          mountPath: /etc/cloudflare.ini
          subPath: cloudflare.ini
          readOnly: true
      imagePullSecrets:
      - name: dockerconfigjson
      volumes:
      - name: conf
        persistentVolumeClaim:
          claimName: certbot
      - name: cloudflare
        secret:
          secretName: nuc
          items:
          - key: cloudflare
            path: cloudflare.ini
      restartPolicy: Never
  backoffLimit: 4
