---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: certbot
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/certbot
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certbot
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi