apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.azof.fr/azoff/nginx:1.1.2
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: certs
          mountPath: /etc/letsencrypt
      volumes:
      - name: certs
        persistentVolumeClaim:
          claimName: certbot
      imagePullSecrets:
      - name: dockerconfigjson
