apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.azof.fr/azoff/nginx:1.0.6
        ports:
        - containerPort: 80
        - containerPort: 443
      imagePullSecrets:
      - name: dockerconfigjson
